import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import moment from 'moment';

export interface HealthReportData {
  userName: string;
  dateRange: { start: Date; end: Date };
  cycles: Array<{
    startDate: string;
    endDate: string | null;
    length: number;
  }>;
  symptoms: Array<{
    date: string;
    type: string;
    severity: 'Low' | 'Medium' | 'High';
  }>;
}

export const HealthReportService = {
  /**
   * Generates an HTML template for the report
   */
  generateHtml: (data: HealthReportData) => {
    const { userName, dateRange, cycles, symptoms } = data;
    
    const formattedStart = moment(dateRange.start).format('MMM D, YYYY');
    const formattedEnd = moment(dateRange.end).format('MMM D, YYYY');

    const cycleRows = cycles.map(cycle => `
      <tr>
        <td>${moment(cycle.startDate).format('MMM D, YYYY')}</td>
        <td>${cycle.endDate ? moment(cycle.endDate).format('MMM D, YYYY') : 'Ongoing'}</td>
        <td>${cycle.length} days</td>
      </tr>
    `).join('');

    const symptomRows = symptoms.map(symptom => `
      <tr>
        <td>${moment(symptom.date).format('MMM D, YYYY')}</td>
        <td>${symptom.type}</td>
        <td><span class="badge ${symptom.severity.toLowerCase()}">${symptom.severity}</span></td>
      </tr>
    `).join('');

    return `
      <!DOCTYPE html>
      <html>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
          <style>
            body { font-family: 'Helvetica', sans-serif; color: #333; padding: 40px; }
            h1 { color: #E91E63; margin-bottom: 5px; }
            h2 { color: #555; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-top: 30px; }
            .header { margin-bottom: 40px; }
            .meta { color: #666; font-size: 14px; }
            table { width: 100%; border-collapse: collapse; margin-top: 15px; }
            th { text-align: left; background: #f8f9fa; padding: 12px; font-size: 12px; text-transform: uppercase; color: #666; }
            td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
            .badge { padding: 4px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
            .badge.low { background: #e3f2fd; color: #1565c0; }
            .badge.medium { background: #fff3e0; color: #ef6c00; }
            .badge.high { background: #ffebee; color: #c62828; }
            .footer { margin-top: 50px; font-size: 10px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Health Report</h1>
            <div class="meta">Generated for <strong>${userName}</strong></div>
            <div class="meta">Period: ${formattedStart} - ${formattedEnd}</div>
          </div>

          <h2>Cycle History</h2>
          <table>
            <thead>
              <tr>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Length</th>
              </tr>
            </thead>
            <tbody>
              ${cycleRows || '<tr><td colspan="3">No cycle data available for this period.</td></tr>'}
            </tbody>
          </table>

          <h2>Symptom Log</h2>
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Symptom</th>
                <th>Severity</th>
              </tr>
            </thead>
            <tbody>
              ${symptomRows || '<tr><td colspan="3">No symptoms logged for this period.</td></tr>'}
            </tbody>
          </table>

          <div class="footer">
            <p>Generated by Women's Health App • Private & Confidential</p>
            <p>This report is for informational purposes only and does not constitute medical advice.</p>
          </div>
        </body>
      </html>
    `;
  },

  /**
   * Generates PDF and opens share dialog
   */
  exportReport: async (data: HealthReportData) => {
    try {
      const html = HealthReportService.generateHtml(data);
      
      const { uri } = await Print.printToFileAsync({
        html,
        base64: false
      });

      await Sharing.shareAsync(uri, {
        UTI: '.pdf',
        mimeType: 'application/pdf',
        dialogTitle: 'Share Health Report'
      });

    } catch (error) {
      console.error('Failed to generate report:', error);
      throw error;
    }
  }
};